
esphome:
  name: hdl1500ps60-test
  comment: test
  project:
    name: "tylerjwatson.chargy3"
    version: 1.0.0

logger:
  level: INFO

mdns:

ota:

mqtt:
  broker: 10.0.0.5
  reboot_timeout: 0s

api:

web_server:
  port: 80

wifi:
  ssid: IoT
  password: Int3rnets
  fast_connect: true

esp8266:
  board: esp8285
  restore_from_flash: true

uart:
- id: test
  rx_pin: GPIO14
  tx_pin: GPIO13
  baud_rate: 4800
  data_bits: 8
  stop_bits: 1
  parity: NONE
  
  # debug:
  #   direction: BOTH
  #   after:
  #     delimiter: "\r\n"
  #   sequence:
  #     - lambda: UARTDebug::log_string(direction, bytes);

hdxps:
  id: hdxps0
  uart_id: test
  output_enabled: false
  update_interval: 10s


text_sensor:
  - platform: hdxps
    device_id: hdxps0
    identity:
      name: 'SMPS Identity'

binary_sensor:
  - platform: hdxps
    device_id: hdxps0
    otp_shutdown:
      name: 'OTP Shutdown'
    ovp_shutdown:
      name: 'OVP Shutdown'
    olp_shutdown:
      name: 'OLP Shutdown'
    high_temp_alarm:
      name: 'High Temperature Alarm'
    fan_failure:
      name: 'Fan Failure'

switch:
  - platform: gpio
    pin: GPIO5
    name: MeanWell Output Enabled

  - platform: hdxps
    device_id: hdxps0
    control:
      name: Remote Control Mode
      restore_mode: RESTORE_DEFAULT_ON
    output_enabled:
      name: Output Enabled

number:
  - platform: hdxps
    device_id: hdxps0
    voltage:
      name: 'Target Voltage'
      mode: box
    current:
      name: 'Target Current'
      mode: box

sensor:
  - platform: uptime
    name: Uptime
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 60s

  - platform: hdxps
    device_id: hdxps0
    temperature:
      name: 'Temperature'
    rated_voltage:
      name: 'Rated Voltage'
    rated_current:
      name: 'Rated Current'

    output_voltage:
      name: 'Output Voltage'
    output_current:
      name: 'Output Current'

