
esphome:
  name: hdl1500ps60-test
  comment: test
  project:
    name: "tylerjwatson.chargy3"
    version: 1.0.0

logger:
  level: DEBUG

mdns:

ota:

web_server:
  port: 80

wifi:
  ssid: IoT
  password: Int3rnets

esp8266:
  board: esp8285
  restore_from_flash: true

uart:
- id: test
  rx_pin: GPIO14
  tx_pin: GPIO13
  baud_rate: 4800
  data_bits: 8
  stop_bits: 1
  parity: NONE
  # debug:
  #   direction: BOTH
  #   after:
  #     delimiter: "\r\n"
  #   sequence:
  #     - lambda: UARTDebug::log_string(direction, bytes);

hdxps:
  id: hdxps0
  uart_id: test
  voltage: 55.2
  current: 0
  output_enabled: false
  update_interval: 10s


text_sensor:
  - platform: hdxps
    device_id: hdxps0
    serial:
      name: 'SMPS Serial'
